services:
  account-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/http.d/default.conf
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TZ=Europe/London
      - DB_URL=${DB_URL}
    restart: unless-stopped 