"""unique constraint

Revision ID: 00e021905c99
Revises: e247ac10f43f
Create Date: 2025-02-24 16:16:33.543125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e021905c99'
down_revision: Union[str, None] = 'e247ac10f43f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bank_transactions', ['date', 'sender', 'receiver', 'description', 'amount', 'currency'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bank_transactions', type_='unique')
    # ### end Alembic commands ###
